### ISSUE TITLE
Doesn't work on Samsung S20 FE 5G

### ISSUE THREAD

**Issue by protist** [mueller-ma/Coffee#116]
**Describe the bug**
This doesn't work on my device (Samsung S20 FE 5G). I installed Coffee 1.18 from F-Droid, and disabled Battery Optimisation. After my normal screen timeout duration, the screen turns off like normal.

FWIW [Caffeine - Keep Screen On](https://play.google.com/store/apps/details?id=moe.zhs.caffeine) works fine on my device. This suggests that perhaps this issue fixable, but unfortunately that app is closed-source, so it might be hard to emulate.

**To Reproduce**
1. Go to the Android menu in the status bar
2. Tap on Coffee Quick Tile
3. Wait for timeout duration

**Expected behavior**
Screen should stay on.

**Observed behavior**
Screen turns off.

**Device (please complete the following information):**
 - Device: Samsung S20 FE 5G
 - Android version: 11

**Comment by Nickoriginal** [comment]
Please see [this](https://github.com/mueller-ma/Coffee/blob/main/fastlane/metadata/android/en-US/full_description.txt) from the 8th line and multiple [closed](https://github.com/mueller-ma/Coffee/issues?q=is:issue+is:closed) issues about the screen turning off. Also please visit [this](https://dontkillmyapp.com) site to learn what to do with your problem. As I understood, main fault lies on the Samsung, Xiaomi, Oppo and other vendors, that kill apps not in the foreground. If this is a bug, it can not be fixed right now.

**Comment by protist** [comment]
Thanks @Nickoriginal. Yep, I was aware that there were many closed issues here, but I just wanted to (a) add the S20 to the list and (b) add some more information about an alternative app (Caffeine - Keep Screen On) that *does* seem to work on my phone. Even though Samsung is obviously quite poor with killing apps, it seems that that other apps do somehow manage to work around this.

To add to my original report, I also did more testing, and if I leave Coffee running in the foreground, it does indeed prevent my phone from sleeping.

**Comment by KrasnayaPloshchad** [comment]
On Google Play there is an app [Stay Alive!](https://play.google.com/store/apps/details?id=com.synetics.stay.alive) provides an option “Use altername screen alive method”, which is claimed to be works on Xiaomi devices.

**Comment by mueller-ma** [comment]
Can you check out this apk? It has an alternate mode implemented, that must be enabled in the settings:

[coffee-debug.zip](https://github.com/mueller-ma/Coffee/files/8596787/coffee-debug.zip)

You need to rename it to .apk first.

**Comment by protist** [comment]
Thank you @mueller-ma . This works perfectly on my phone!
