### ISSUE TITLE
Implement safety features

### ISSUE THREAD

**Issue by AlCooo** [mueller-ma/Coffee#118]
**Is your feature request related to a problem? Please describe.**
Sometimes I forget that I had Coffee turned on. It may be stolen by others or the battery may be used up, so I would be grateful if you could implement a feature to prevent it.

**Describe the solution you'd like**
Implement these features:
* Blink the notification LED when turned on (eg at 1Hz)
* Vibrate or play sound periodically when turned on
* Add timer (Allow awake time to be set to a limited time)
The timer feature has been rejected at https://github.com/mueller-ma/Coffee/issues/38, but I think it can be solved by providing an option in the app instead of using a tile to adjust the time.

Also, I submitted a Japanese translation on Crowdin. If you like, please approve the translation or give me permission to approve it.

**Comment by mueller-ma** [comment]
Currently there are two features that improve the security:
1. There is a persistent notification.
1. Coffee turns of when the screen is locked.


I could think of having a preference screen with the notification LED and the timer. I'm not sure about the vibration/sound.

I gave you proofreader permissions for Japanese on Crowdin.

**Comment by AlCooo** [comment]
Thank you!

For me, the current safety features are inadequate.
The notification is less noticeable than the LED.
Turning it off when locked is a nice feature, but conversely if I forget to lock it manually it will stay on until the battery runs out.

Additional explanation:
The timer I want is the feature to turn off Coffee when the device has been inactive for a set amount of time (like Android's screen timeout). It is not a feature that turns off Coffee in a certain amount of time regardless of whether or not the device is used.
Sorry for the ambiguous explanation.

**Comment by mueller-ma** [comment]
> I think it can be solved by providing an option in the app instead of using a tile to adjust the time.

I added a timer setting https://github.com/mueller-ma/Coffee/commit/45d9dbf27f678916df381f062476a00704a550f1 and the LED request will follow.

**Comment by mueller-ma** [comment]
The LED isn't used as long as the screen is on: https://stackoverflow.com/a/14593751/13139982

Therefore it cannot be used here.

**Comment by AlCooo** [comment]
> I added a timer setting https://github.com/mueller-ma/Coffee/commit/45d9dbf27f678916df381f062476a00704a550f1

Thank you!

> The LED isn't used as long as the screen is on

Oh, I see.
I hope you will consider again adding a periodic vibration setting.

**Comment by mueller-ma** [comment]
TBH I'm not a fan of the periodic vibration idea.
