### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by E0697** [mueller-ma/Coffee#136]
**Describe the bug**
The app is crashing when I press 'help'.
There's another instance of crashing listed below.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Stop coffee after'
3. The app relaunches

**Expected behavior**
Opens timer settings

**Device (please complete the following information):**
 - Device: Realme 7 Pro
 - Android version: 11

**Additional context**

**Comment by mueller-ma** [comment]
Can you update to version 2.1 (when it's available on F-Droid) and capture the ADB log?

**Comment by E0697** [comment]
Just updated to 2.1.0
I had to allow Coffee to run in the background and disable battery optimization for it to work. I'll test the alternate mode now.
It's still crashing when trying to access the timer settings tho.
Logs: https://bin.disroot.org/?819d93fc72d1990c#ApTp22xVvNf5NgSqRrGoWdGmdyPpz2jGQcoqXaSRhFPG

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall Coffee if installed
- Install my apk

[app-debug.zip](https://github.com/mueller-ma/Coffee/files/8654607/app-debug.zip)

**Comment by E0697** [comment]
The debug apk doesn't crash.
Thank you for the fix.
