### ISSUE TITLE
Add option to hide app from the app drawer

### ISSUE THREAD

**Issue by S-Sajith** [mueller-ma/Coffee#142]
Would it be possible to add an option to hide the app from the app drawer ?

**Comment by ricoyp96** [comment]
Agree

**Comment by Shanta-11** [comment]
hey, can I work on this??

**Comment by mueller-ma** [comment]
Sure

**Comment by Shanta-11** [comment]
> Sure

Are there any contributing guidelines I should follow?

**Comment by mueller-ma** [comment]
There should be a new toggle in the settings menu. When accessing SharedPreferences from code, use `Prefs.kt`.

**Comment by VedantpD** [comment]
hey I am a beginner , Can I work on this ?

**Comment by mueller-ma** [comment]
Sure, you can open a PR with your code.

**Comment by VedantpD** [comment]
> Sure, you can open a PR with your code.

Can I after 1st Oct as I want to participate in Hactoberfest.
