### ISSUE TITLE
QS tile no longer available.

### ISSUE THREAD

**Issue by E0697** [mueller-ma/Coffee#145]
**Describe the bug**
I reported the crashing earlier, and it was fixed in v2.2, however, starting from v2.2, the QS tile is not available anymore.
**To Reproduce**
1. Go to quick settings edit mode
2. No coffee tile available

**Expected behavior**
I had previously added the tile when I was using v2.1, so when I updated the app it was still there.
After restarting the phone however, it turned into a blank tile (it still works, screenshot attached) and if I remove I can't add it again.

**Screenshots**
![IMG_20220523_193050](https://user-images.githubusercontent.com/66939100/169866199-043b84d1-e897-446e-a494-12d2d62a1e50.jpg)

![IMG_20220523_193059](https://user-images.githubusercontent.com/66939100/169866230-e02b9a7f-0910-4297-a20e-ead93e77e5b0.jpg)

**Device (please complete the following information):**
 - Device: Realme 7 Pro
 - Android version: 11

**Additional context**
One more thing, coffee's icon is blank in the settings (normal in launcher when using default icon shape).

**Comment by E0697** [comment]
Blank icon
![IMG_20220523_193059](https://user-images.githubusercontent.com/66939100/169866333-21fc43b4-34df-4502-9a7d-e41fb32c8c9e.jpg)

**Comment by E0697** [comment]
I tried that. Installed v2.3, no tile available. Tried rolling back to v2.1 and it was available again, updated to v2.3 then restarted then it happens as the screenshot.

**Comment by mueller-ma** [comment]
Ok, thanks for testing this. I'm not sure what can cause such an issue. I'll investigate that.

**Comment by E0697** [comment]
Thank you!

**Comment by mueller-ma** [comment]
I wasn't able to reproduce this issue, but version 2.5 contains improvements to the quick tile. Please reopen if the issue still exists for you.

**Comment by E0697** [comment]
I just updated to Android 12 and it's all good now. The QS tile is available again. Thank you!
