### ISSUE TITLE
More easily trigger timeouts of various lengths

### ISSUE THREAD

**Issue by jmalexan** [mueller-ma/Coffee#149]
**Is your feature request related to a problem? Please describe.**
It's inconvenient to only be able to adjust how long the timeout triggered by the QS tile is by going into the settings and changing the option there.  It's often the case that I'll want to use different timeouts, e.g. keep my phone awake endlessly while I'm running an idle game at my desk, vs keeping the phone awake for 5 minutes while reading through some long piece of text on the screen.

**Describe the solution you'd like**
Tapping and holding on the QS tile should bring up options for how long to set the timeout for the activation about to be done.  The single tap behavior could be based on some default (set in the settings) or the last used timeout.

**Comment by mueller-ma** [comment]
Can you check 2.4 (when it's on F-Droid) and give feedback if the notification action is suitable?
