### ISSUE TITLE
Quick Tile Background Does Not Invert/Revert According to the Theme

### ISSUE THREAD

**Issue by beaglesnuf** [mueller-ma/Coffee#153]
**Describe the bug**
Coffee is enabled/disabled but inversion of quick tile indicating either enabled/disabled is not visible until notification shade is closed and then opened again.

**To Reproduce**
1. Coffee disabled > Click Cofee quick tile to enable 
2. Coffe enabled > click Coffee quick tile to disable 

**Expected behavior**
If disabled, clicking the Coffee quick tile will invert according to the current theme to provide visual feedback that the wake-lock has been enabled. if enabled, clicking Coffee quick tile will revert according to the current theme to provide visual feedback that the wake-lock has been disabled.

**Device (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android version: 12.1

**Additional context**
GrapheneOS

**Comment by mueller-ma** [comment]
I'm not aware of any quick tile theming in AOSP, so that's a feature of GrapheneOS? Maybe some special code is required here.

I had a similar issue on my device but fixed it by removing and re-adding the quick tile. Can you check that?

**Comment by beaglesnuf** [comment]
> I'm not aware of any quick tile theming in AOSP, so that's a feature of GrapheneOS? Maybe some special code is required here.

Monet. Though the issue also exists with Monet disabled.

> I had a similar issue on my device but fixed it by removing and re-adding the quick tile. Can you check that?

Tried. Does not resolve the issue. AV1 screen record of what happens: https://envs.sh/QDv.webm

**Comment by mueller-ma** [comment]
I wasn't able to reproduce this issue, but version 2.5 contains improvements to the quick tile. Please reopen if the issue still exists for you.

**Comment by de-souza** [comment]
I was experiencing this issue with a Pixel 6A on GrapheneOS until today, and the last release of Coffee (2.19) fixed it.
