### ISSUE TITLE
Quick Setttings Tile disabled after reboot or update

### ISSUE THREAD

**Issue by LukasThyWalls** [mueller-ma/Coffee#159]
**Describe the bug**
The Quick Settings Tile for Coffee is set and working, but when i reboot the phone, the tile is disabled and i can toggle it (although i can open Coffee if i hold in it). The only way to enable it again is remove the tile and put it again.
Also i think happens when Coffee updates, but i need to see it again to confirm it.

**To Reproduce**
1. Set the tile for Coffee. Test it's working.
2. Reboot the phone. (Also i think it happens when Coffee updates).
3. The tile now is disabled. You can't toggle directly there now.
4. Remove the tile, and press ok. Open again Quick Settings to put it again.
5. It works again.

**Expected behavior**
The tile should be enabled always, after the phone is rebooted (or it updates).

**Screenshots**
Working tile:
![1657093519203](https://user-images.githubusercontent.com/1467366/177502212-8d26084a-5a7a-4307-8a3e-6bd92d6a0fa9.jpg)

Tile after a reboot:
![1657093519212](https://user-images.githubusercontent.com/1467366/177502252-5aa99138-5b32-4363-8e1e-ebce86a66d65.jpg)

The only option is to remove the tile and put it again.

**Device (please complete the following information):**
 - Device: Xiaomi Mi 9 Lite
 - Android version: 10 (MIUI 12.0.10/QKQ1.190828.002)
 - Coffee 2.4 installed via F-Droid.

**Additional context**
It's something i detected at least a month ago, but i was occupied and forgot to report it.

Thanks!

**Comment by mueller-ma** [comment]
I wasn't able to reproduce this issue, but version 2.5 sets the correct tile state after reboot.

**Comment by LukasThyWalls** [comment]
Yesterday, Coffee was updated via F-droid and i can confirm that the tile still works after the update.

However, it stills doesn't work when you reboot the phone. You need to delete and put the tile again to make it work.

**Comment by mueller-ma** [comment]
Is Coffee installed on external storage on your device?

**Comment by LukasThyWalls** [comment]
> Is Coffee installed on external storage on your device?

No, I don't know if I can do it anyway in this Android version, but I don't have to do it because I have tons of internal storage.

To update the specs:

* Device: Xiaomi Mi 9 Lite (Octa-Core 2.2 Ghz, 6GB RAM, 41 used/64 GB Internal storage, 22 used/32 GB external storage)
* Android version: 10 (MIUI 12.0.10/QKQ1.190828.002)
* Coffee 2.5 installed via F-Droid. (Installed on internal storage)

**Comment by penn5** [comment]
Reproduced on Redmi Note 5 (MIUI 12.0.2, Coffee 2.5, install location not checked) but not on Mi 9 (MIUI 12.5.1, Coffee 2.6, internal storage).

**Comment by LukasThyWalls** [comment]
> Reproduced on Redmi Note 5 (MIUI 12.0.2, Coffee 2.5, install location not checked) but not on Mi 9 (MIUI 12.5.1, Coffee 2.6, internal storage).

In my case with 2.6 still happens.

I tested if it can be related to the fingerprint and device password security, but with them disabled it stills do the same (Before the SIM Pin you can't access the quick settings, but after the PIN you can access the tiles and the Coffee one is disabled. Fingerprint and device password comes in that moment).

**Comment by penn5** [comment]
The Note 5 has SIM lock enabled while my Mi 9 doesn't. This fits.

**Comment by LukasThyWalls** [comment]
For me doesn't seem related because i disabled everything (PIN, Fingerprint, Device password) and it still does the same.

**Comment by penn5** [comment]
Indeed, removing SIM lock did not fix the issue

**Comment by mueller-ma** [comment]
I tried several configurations, but I always have the following behavior:

- Reboot => Tile is disabled
- First unlock after reboot => Tile will be enabled


Can you please test the following apk? It has direct boot enabled, which could improve the issue for you.

- Rename it to .apk
- Install my apk

[coffee.zip](https://github.com/mueller-ma/Coffee/files/9206878/coffee.zip)

**Comment by penn5** [comment]
Installing this apk changed nothing :/

**Comment by LukasThyWalls** [comment]
> [coffee.zip](https://github.com/mueller-ma/Coffee/files/9206878/coffee.zip)

No change. The tile was enabled, I have rebooted the phone, and the tile is disabled again after the reboot. As explained above, you need to delete it add it again to the tiles to make it enabled again, so, the same behaviour.

**Comment by LukasThyWalls** [comment]
Hello.

Only to add that since a few updates, i can't precise when, for me the updates don't disable the tile.

However, rebooting the phone do the same, i still need to remove and put back the tile to make it work.

**Comment by mueller-ma** [comment]
This is most likely a vendor-specific problem that I cannot debug without a Xiaomi device :/

**Comment by LukasThyWalls** [comment]
Understandable.

The only thing I can say is with Coffee 2.21 still do this when there is a reboot. With the latest updates I wasn't aware if it disables the tile or not. Everything else works.

Thanks anyway!
