### ISSUE TITLE
I have to click several times (on the shortcut in the notifications) to activate Coffee

### ISSUE THREAD

**Issue by Darkempire78** [mueller-ma/Coffee#164]
**Describe the bug**
I need to click several times on the shortcut in the notifications (sometimes something like 8-10 click) to activate Coffee

**To Reproduce**
1. Click on the shortcut
2. Cry

**Expected behavior**
Click one time to run Coffee

**Device (please complete the following information):**
 - Device: Pixel 6
 - Android version: 12

**Comment by Darkempire78** [comment]
To be sure, I'm talking about that (It is in French here) :
![image](https://user-images.githubusercontent.com/50015928/179375364-ce372465-7131-4c3b-b3a2-134bd56a52b9.png)

**Comment by mueller-ma** [comment]
How do you know Coffee doesn't start after clicking the tile the first time?

This could be related to deferred visibility of the notification: https://developer.android.com/reference/android/app/Notification.Builder#setForegroundServiceBehavior(int)

**Comment by Darkempire78** [comment]
@mueller-ma when I click I have no notification and the tile does not color

**Comment by Darkempire78** [comment]
I'm testing and in fact it sometimes seems to take several seconds to start 😅

**Comment by mueller-ma** [comment]
> This could be related to deferred visibility of the notification: https://developer.android.com/reference/android/app/Notification.Builder#setForegroundServiceBehavior(int)

Added in https://github.com/mueller-ma/Coffee/commit/6391f86d09d403374fd5e735527672082cb407f7
