### ISSUE TITLE
App icon in Android 12 dark mod

### ISSUE THREAD

**Issue by Bolsderac** [mueller-ma/Coffee#183]
See attachment.
Android 12 oneplus 7.

![IMG_1662683219709](https://user-images.githubusercontent.com/60016981/189248356-03067384-c28e-4556-ad37-27c3be92b607.jpg)

**Comment by mueller-ma** [comment]
Can you fill out the issue template?

**Comment by d4f5409d** [comment]
I'm having the same issue.

**Comment by mueller-ma** [comment]
> Device (please complete the following information):
> 
>  *  Device: OnePlus 8
>  *  Android version: 12

from https://github.com/mueller-ma/Coffee/issues/202

**Comment by mueller-ma** [comment]
Can you test the following apk? 

- Rename it to .apk
- Install my apk


[app-debug.zip](https://github.com/mueller-ma/Coffee/files/9895645/app-debug.zip)

**Comment by d4f5409d** [comment]
It works.
![Screenshot_2022-10-30-12-25-03-99_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/76624594/198875986-493608be-78e9-48e6-a6bd-ca0df0965e25.jpg)
