### ISSUE TITLE
Disable auto-turn-off on screen lock

### ISSUE THREAD

**Issue by Wjxfi** [mueller-ma/Coffee#186]
App version: 2.8
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2263 x 1078
MIUI 13.0.5

**Comment by JonnyTech** [comment]
The latest version is 2.8, please try with that:

https://f-droid.org/en/packages/com.github.muellerma.coffee/

**Comment by mueller-ma** [comment]
> App version: 1.3.2 (10320)

There was no version 1.3.2 for this app. Are you sure you're using Coffee?

If so, did you enable alternate mode?

**Comment by mueller-ma** [comment]
Closed due to inactivity

**Comment by mueller-ma** [comment]
Can you try it again with 2.11 and the issue still persists, capture a log via adb?

**Comment by mueller-ma** [comment]
Can you capture the log via adb? Does the notification show up when Coffee is activated?

**Comment by mueller-ma** [comment]
> but it disappears after the screen is turned off

Do you turn off the screen manually, e.g. by pressing the lock button?

**Comment by mueller-ma** [comment]
When you lock the screen manually, Coffee turns off. This is intentional behavior.

**Comment by mueller-ma** [comment]
I wouldn't veto against a switch in the settings to make this optional. However I don't know if a wakelock can survive the manual screen lock.
