### ISSUE TITLE
Notifications disabled for Coffee

### ISSUE THREAD

**Issue by dino-** [mueller-ma/Coffee#195]
**Describe the bug**
Notifications do not work and can't be turned on for Coffee.

**To Reproduce**
Toggle Coffee on with the tile. Observe no notification.

**Expected behavior**
A notification explaining Coffee is active should appear in the notifications. In app notifications settings it says "At your request, Android is blocking this app's notifications from appearing on this device". The toggle can't be changed.

**Screenshots**
![Screenshot_20221016-081607.png](https://user-images.githubusercontent.com/223001/196036181-0f4d2d55-a3c0-4bfe-9679-44bff97467c1.png)

**Device (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android version: 13

**Additional context**
Investigation shows this is a widespread problem with Android 13 and many apps. I'm not sure but have read there may be a change to permissions involved somehow.
I did try 'System -> Reset options -> Reset app preferences' to no avail. Also tried clearing app data, rebooting and uninstall/reinstall.

**Comment by mueller-ma** [comment]
Android 13 requires a new permission before notifications are shown. This permission must be requested by Coffee.

**Comment by jpjonte** [comment]
I started having this issue when I upgraded Coffee to version 2.9 (on Android 13). It works fine when I install version 2.8, where I get the permission popup. That is very strange since 2.9 is supposed to add support for Android 13.
