### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by shuvashish76** [mueller-ma/Coffee#20]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I open & toggle WiFi, Bluetooh etc from quick settings because my device is a 8inch tablet. Its not very convenient to drag the notification bar in bigger size devices or tablets].

**Describe the solution you'd like**
It would be nice to have a widget in home screen which can does the same job.

**Additional context**
ideas for widget: maybe a widget like [Night Screen](https://github.com/fython/Blackbulb) or transparent widget like [Habits](https://github.com/iSoron/uhabits) would look great.

![Screenshot_2020-12-07-05-15-05](https://user-images.githubusercontent.com/48226312/101296772-57b34080-384b-11eb-912c-e565c1cd6234.jpeg)

Thanks🙏🏿

**Comment by mueller-ma** [comment]
Technically I didn't add a widget, but a shortcut. It should behave the same way and looks a bit nicer.
