### ISSUE TITLE
video mode

### ISSUE THREAD

**Issue by Wjxfi** [mueller-ma/Coffee#203]
**Describe the solution you'd like**
video mode

During video playback, the screen does not turn off. this will help

**Additional context**

preferably invisible video

**Comment by mueller-ma** [comment]
Apps running in foreground, e.g. during video playback, set the flag `WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON` to keep the screen on.
Coffee should keep the screen on when it's not in foreground, so this wouldn't work.
