### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/Coffee#208]
Please add an option to disable notification on app settings:

![Screenshot_2022-11-11-00-49-30-904_com.github.muellerma.coffee.jpg](https://user-images.githubusercontent.com/23485114/201208562-0269bf65-4aa6-422b-866e-80f77f793641.jpg)

**Comment by mueller-ma** [comment]
The notification is required to hold a wake lock when Coffee is in background.
