### ISSUE TITLE
Show remaining time

### ISSUE THREAD

**Issue by BartG95** [mueller-ma/Coffee#218]
**Is your feature request related to a problem? Please describe.**
I can't see the remaining time.

**Describe the solution you'd like**
I would like to see the remaining time.
Some suggested placess (maybe all):
- in the app itself
- in the notification
- in the quick tile

**Describe alternatives you've considered**
When turning Coffee on, a notification pops up. As with all notifications, it shows how long ago the it was created, essentially showing how long ago Coffee was turned on. One can know the remaining time from subtracting the chosen timeout with this time.

**Additional context**
Some inspiration: the quick tile in LineageOS.

**Comment by mueller-ma** [comment]
With https://github.com/mueller-ma/Coffee/commit/b38548fcf4519528ab70695d178cdf760575eeb0 the remaining time is shown in the tile and the app itself. Notification is still missing.
