### ISSUE TITLE
Allow changing the timeout by tapping the quick tile again

### ISSUE THREAD

**Issue by BartG95** [mueller-ma/Coffee#219]
**Is your feature request related to a problem? Please describe.**
As it is now: tap the QT to enable Coffee, then repeatably tap the "Next Timeout" on the notification to change the timeout.

**Describe the solution you'd like**
This should be doable by tapping the QT itself, so it all in one place.

**Describe alternatives you've considered**
N/A

**Additional context**
- See LineageOS for some inspiration.
- This should probably an option. I know some people just want their QT to be an on/off toggle.
- This depends on the QT showing the remaining time, see #218 .

**Comment by mueller-ma** [comment]
Duplicate of #206
