### ISSUE TITLE
Request Accrescent as a Store

### ISSUE THREAD

**Issue by beaglesnuf** [mueller-ma/Coffee#224]
**Is your feature request related to a problem? Please describe.**
F-droid remains the sole option for pre-built binaries.

**Describe the solution you'd like**
Publish on [Accrescent](https://accrescent.app/) as a secure delivery method for A12 devices and above. No need to upload your signing key. 

**Describe alternatives you've considered**
None which do not require the dev signing key

**Additional context**
APK built as a split and support for unattended updates.

**Comment by mueller-ma** [comment]
For now I'll keep F-Droid as only option. I'd rather add a new repo that will act as F-Droid repo with my singing keys for my apps.

**Comment by mueller-ma** [comment]
You can download the apk from GitHub now: https://github.com/mueller-ma/Coffee/releases
