### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by xmha97** [mueller-ma/Coffee#231]
Hi @mueller-ma 
Please upload APK files to GitHub release.
Play Store and F-Droid and VPNs blocked on my country and I can't update this app.
Thanks 🙏

**Comment by JonnyTech** [comment]
You cannot access directly? https://f-droid.org/repo/com.github.muellerma.coffee_33.apk

**Comment by mueller-ma** [comment]
I'd rather setup a F-Droid repo for all of my apps that lives in a GitHub repo and is deployed to GitHub pages. Help is welcomed :)

I saw that someone did something similar in GitLab: https://gitlab.com/rfc2822/fdroid-firefox

**Comment by xmha97** [comment]
> You cannot access directly? https://f-droid.org/repo/com.github.muellerma.coffee_33.apk

No

**Comment by shuvashish76** [comment]
> Play Store and F-Droid and VPNs blocked on my country

F-Droid official onion service mirror : https://gitlab.com/fdroid/admin/-/issues/12#note_1184095205

**Comment by xmha97** [comment]
> > Play Store and F-Droid and VPNs blocked on my country
> 
> F-Droid official onion service mirror : https://gitlab.com/fdroid/admin/-/issues/12#note_1184095205

Onion (Tor network) is blocked on my country...

**Comment by JonnyTech** [comment]
Have you tried all the fdroid mirrors listed here?: https://gitlab.com/fdroid/mirror-monitor/-/raw/master/README.md

**Comment by xmha97** [comment]
Yes,

![Screenshot_2023-03-09-12-17-46-527_org.fdroid.fdroid.jpg](https://user-images.githubusercontent.com/23485114/223968845-e09e531c-4ad6-4fe1-a050-bbf45ed95548.jpg)

**Comment by JonnyTech** [comment]
> Yes

Wow. Which country hates fdroid so much?

**Comment by xmha97** [comment]
> > Yes
> 
> Wow. Which country hates fdroid so much?

Iran 🇮🇷

Hates F-Droid because of their VPNs like ProtonVPN.

Hates VPN because they want to keep the news monopolized and exclude the opposition.

**Comment by mueller-ma** [comment]
You can download the apk from GitHub now: https://github.com/mueller-ma/Coffee/releases

Can you give it a try? Then I can copy this script to my other apps.

**Comment by xmha97** [comment]
> You can download the apk from GitHub now: https://github.com/mueller-ma/Coffee/releases
> 
> Can you give it a try? Then I can copy this script to my other apps.

Thanks 🙏
