### ISSUE TITLE
Misnotification

### ISSUE THREAD

**Issue by sls1005** [mueller-ma/Coffee#232]
**Describe the bug**

The app's notification says it's turned off, while it's actually turned on. The whole message was
>Turned off
>Tap to turn off

**To Reproduce**
1. Turn on Coffee

**Expected behavior**
>Coffee is turned on
>Tap to turn off

**Device:**
 - Device: Samsung M33 5G (SM-M336B)
 - Android version: 13

**Comment by mueller-ma** [comment]
Indeed! It worked well in an emulator and after the rollout I discovered this bug :/
