### ISSUE TITLE
After enabling Coffee app also my screen turnsoff. My mobile is Samsung A30, running oneUI 2.0 based on Android 10. 

### ISSUE THREAD

**Issue by selva-1106** [mueller-ma/Coffee#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - Android version: [e.g. 11]

**Additional context**

**Comment by mueller-ma** [comment]
Duplicate of  #16.
