### ISSUE TITLE
color change of the coffe button might be useful 

### ISSUE THREAD

**Issue by paulle** [mueller-ma/Coffee#246]
I like coffee because in s lot situations it's very useful.
I use the button on my start screen for switching coffee on/off.
It would be very handy if this button would change the colour, depending on coffee is on or off. So at one glance one can see coffee is active or not.

**Comment by mueller-ma** [comment]
Can you post a screenshot of that button?

**Comment by paulle** [comment]
Gesendet von Proton Mail für Mobilgeräte

Yes

-------- Original-Nachricht --------
Am 16. Apr. 2023, 19:27, schrieb mueller-ma :

**Comment by paulle** [comment]
![Screenshot_20230416-192923](https://user-images.githubusercontent.com/4852079/232330425-5eb244c0-326c-421f-9f93-bbcc971fef18.png)

**Comment by paulle** [comment]
The button is always white, it could be helpful if it switches to another colour when coffee is active

**Comment by mueller-ma** [comment]
AFAIK these shortcuts cannot be edited after they have been created.

**Comment by paulle** [comment]
Ok, sorry but I didn't know this.
Excuse my silly question.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 17. Apr. 2023, 22:15, schrieb mueller-ma :

**Comment by mueller-ma** [comment]
That's not a stupid question, but a valid feature request :)
