### ISSUE TITLE
Coffee always starts at 5 minutes in 2.19

### ISSUE THREAD

**Issue by NathanC** [mueller-ma/Coffee#282]
**Describe the bug**

Coffee used to start at the "stop coffee after" setting, but now, regardless of what I set to it starts at 5 minutes and I have to click it a few times.

**To Reproduce**

1. Set "Stop Coffee After" to 2 hours
2. Click on the tile
3. Note that it starts at 5 minutes, and needs to be clicked a few times to get to 2 hours

**Expected behavior**
The start timeout is what is configured in the settings

**Device (please complete the following information):**
 - Device: Pixel
 - Android version: 13

**Additional context**

I'm not sure if the old behavior (e.g. starting at 2 hours when configured) was intended behavior or not, but I found it very helpful. I usually start coffee in a context where I want the screen to be on for a while

-----

Thanks for creating this! Very useful and simple app.

**Comment by mueller-ma** [comment]
Which quick tile do you use to start Coffee? There are two and one is a toggle (on <=> off) and one cycles through the timeouts.

**Comment by NathanC** [comment]
Ah, I didn't realize there was more than one! Thanks @mueller-ma. Closing this issue, though I will note that the distinction wasn't clear to me—may confuse other users too.

**Comment by mueller-ma** [comment]
Before you add the tiles they are called "Toggle" and "Next timeout". More space for information isn't there, so I guess this situation cannot be much improved.
