### ISSUE TITLE
Tile status inverted

### ISSUE THREAD

**Issue by kirschnj** [mueller-ma/Coffee#283]
**Describe the bug**
When coffee is off, the tile is active (highlighted in green).
Clicking the tile enables coffee and the tile is shown as disabled.

**To Reproduce**
1. Go to tiles
2. Toggle coffee
3. The states of coffee and the tile are inverted.

**Expected behavior**
The tile status and coffee status match. Coffee is activated when the tile is highlighted.

**Device:**
 - Device: Mi A2 Lite
 - Android version: 10

**Comment by mueller-ma** [comment]
Do you use version [2.19](https://github.com/mueller-ma/Coffee/releases/tag/2.19)? Can you force stop the app (in the OS settings go to Coffee and stop it from there) and start it again?

**Comment by kirschnj** [comment]
Yes, this issue appears for me on version 2.19. I tried various steps to cycle the tile button status, including force stop and alternating toggle from the app and the tile.

**Comment by mueller-ma** [comment]
I updated the icon in the tile in https://github.com/mueller-ma/Coffee/releases/tag/2.24. Can you check if that fixes this issue?

**Comment by pdimu** [comment]
@mueller-ma i dint know if this is related, but I think you should take a look here:

https://github.com/user-attachments/assets/03b5f8f6-d166-4f1c-91ae-7a457fdfb339

**Comment by kirschnj** [comment]
> I updated the icon in the tile in https://github.com/mueller-ma/Coffee/releases/tag/2.24. Can you check if that fixes this issue?

The issue stopped appearing for me even on version 2.19. Thanks!

**Comment by mueller-ma** [comment]
@pdimu Can you remove the tile, close the quick settings, add the tile again and see if it works now?

**Comment by pdimu** [comment]
> @pdimu Can you remove the tile, close the quick settings, add the tile again and see if it works now?

@mueller-ma 
Yes, now it works as it should. Thank you for the fix btw
