### ISSUE TITLE
Tile no longer has any image

### ISSUE THREAD

**Issue by Swift8641** [mueller-ma/Coffee#296]
**Describe the bug**
The tile does not display the coffee icon.

**To Reproduce**
1. Install Coffee 
2. Add tile to drawer
3. The tile does not display correctly 

**Expected behavior**
The tile displays the coffee icon.

**Screenshots**
![Screenshot_2023-11-30-12-36-13-17_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/mueller-ma/Coffee/assets/111619933/5fb18a8e-2b2b-45e7-9d7d-b070f599263e)

![Screenshot_2023-11-30-12-36-19-53_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/mueller-ma/Coffee/assets/111619933/05c9da84-1699-41a1-890a-ac9f31f83dee)

**Device (please complete the following information):**
 - Device: OnePlus Nord N30 5G
 - Android version: 13

**Additional context**

**Comment by mrtaxi** [comment]
The same issue on android 13, colorOs

**Comment by mueller-ma** [comment]
I updated the icon in the tile in https://github.com/mueller-ma/Coffee/releases/tag/2.24. Can you check if that fixes this issue?

**Comment by Swift8641** [comment]
It seems to have fixed the issue.
