### ISSUE TITLE
No icon in tile menu

### ISSUE THREAD

**Issue by d4f5409d** [mueller-ma/Coffee#323]
**Describe the bug**
There's an icon missing in the tile menu of Coffee.

**To Reproduce**
1. Add Coffee to the tile menu
2. Experience the issue

**Expected behavior**
An icon to appear.

**Screenshots**
![Screenshot_2024-04-24-18-47-23-79_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/mueller-ma/Coffee/assets/76624594/cde0d474-2ef2-4fed-aa0a-088f2a305967)

**Device (please complete the following information):**
 - Device: OnePlus 8
 - Android version: 13

**Additional context**

**Comment by d4f5409d** [comment]
Duplicate of #236

**Comment by d4f5409d** [comment]
Duplicate of #296

**Comment by mueller-ma** [comment]
I updated the icon in the tile in https://github.com/mueller-ma/Coffee/releases/tag/2.24. Can you check if that fixes this issue?

**Comment by d4f5409d** [comment]
Yes, now ot works
