### ISSUE TITLE
widget should indicate on/off status

### ISSUE THREAD

**Issue by sidmint** [mueller-ma/Coffee#33]
First of all, thank you for this app, it's very useful for me.
If using the widget to toggle, the status is unknown unlike using quick tile. I often forget and check manually via the tile fearing if I left it on then battery will drain.

**Comment by mueller-ma** [comment]
You can manually lock your screen. This will disable coffee as well, so your device won't drain battery.

**Comment by mueller-ma** [comment]
And there's also a persistent notification when Coffee is running. IMO this should be enough.

**Comment by sidmint** [comment]
> And there's also a persistent notification when Coffee is running. IMO this should be enough.

That's okay, I disable/don't use notification things personally until necessary as lots of apps create a ton of garbage there and I've developed a disliking for that area personally, rather I prefer to check via quick tile. Felt that checking widget by going to homescreen might be easier specially if I'm using something fullscreen like commonly with gallery/doc reading apps.

**Comment by mueller-ma** [comment]
I'll look into adding a short message.

**Comment by sidmint** [comment]
> I'll look into adding a short message.

does this belongs to #34?

anyway, i found that the notification way is good as it does the job with 1 click and now using it, earlier i didn't have hoped it to be good like most apps so might have turned it off without trying. Thank you for making the life easy.

**Comment by mueller-ma** [comment]
https://github.com/mueller-ma/Coffee/commit/85dee037ebee3dde8f6a07b42bad4848fcbc3cd3
