### ISSUE TITLE
assist app functionality to toggle it by long pressing home button

### ISSUE THREAD

**Issue by sidmint** [mueller-ma/Coffee#34]
IMO, it would be helpful if I could toggle it just by long pressing the home app. For that it should be present as an option in the list of assist apps, since they can be launched by long pressing the home button.

**Comment by mueller-ma** [comment]
Sure, that's a useful addition.

**Comment by sidmint** [comment]
I don't know whether it's already there, but toggling this way may be complimented by a temporary message display telling whether it has switched on or off. Checking that via notification would require to add more touches if I'm using something fullscreen like commonly with gallery/doc reading apps [and I disable/don't use notification things until necessary personally as lots of apps create a ton of garbage there].

**Comment by sidmint** [comment]
For some reason, it's not available as assisstant app on my Redmi 2 with AOKP rom.

![Screenshot_20210319-090021](https://user-images.githubusercontent.com/43943312/111728050-1858af00-8892-11eb-8df4-b57753caf2b1.png)

**Comment by mueller-ma** [comment]
I totally misunderstood your request, I'll have a look at it.

**Comment by sidmint** [comment]
sorry, but it's not working though being shown.

**Comment by mueller-ma** [comment]
Do you see a toast with "Turned on Coffee"? On my device the assistant is activated differently, but it's working for me.

**Comment by sidmint** [comment]
No toast/notification. Nothing happens. Though that appears happens when I switch it via quick tile and widget. 
And I also checked whether it's working without toast, just in case, but it is not.

**Comment by mueller-ma** [comment]
Can you capture the ADB log?

**Comment by sidmint** [comment]
I'm pasting changes on long pressing home button using `adb logcat`

12-11 07:07:21.642   807  1018 D AutofillManagerService: Close system dialogs
12-11 07:07:21.646  1713  1736 V AssistManager: Voice closed
12-11 07:07:21.660 31472 31472 V View    : dispatchProvideStructure(): not laid out, ignoring 4 children of 1
12-11 07:07:21.660 31472 31472 V View    : dispatchProvideStructure(): not laid out, ignoring 1 children of 2
12-11 07:07:21.675  1713 24546 V AssistManager: Voice open
12-11 07:07:21.707 12216 12216 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3293 
12-11 07:07:21.707 12216 12216 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1981 
12-11 07:07:21.710 12216 12216 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():79 Notify device unlocked.
12-11 07:07:21.729 25453 25473 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
12-11 07:07:21.754 12216 12216 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3293 
12-11 07:07:21.754 12216 12216 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1981 
12-11 07:07:21.755 12216 12216 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():79 Notify device unlocked.
12-11 07:07:21.785 31472 31485 I AssistStructure: Flattened final assist data: 9560 bytes, containing 1 windows, 96 views
12-11 07:07:21.790  1713  2062 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE

**Comment by mueller-ma** [comment]
It seems that Coffee isn't called at all 🤔
