### ISSUE TITLE
Play Protect blocks update to 1.11

### ISSUE THREAD

**Issue by bkircher** [mueller-ma/Coffee#54]
When updating from 1.10 to 1.11 Play Protect blocks the install.

Related to the [assist app changes](https://github.com/mueller-ma/Coffee/commit/50d2dde639e7ce14bd9538e6004b7e43adbd2c9e) maybe?

**Screenshots**
![Screenshot_20210517-060853.png](https://user-images.githubusercontent.com/536464/118431428-a1476780-b6d6-11eb-99e5-bdc58122f944.png)

**Comment by mueller-ma** [comment]
> Related to the assist app changes maybe?

Most likely. Maybe because you can set the app as assist and therefore read the whole screen (the app doesn't do that however).

**Comment by mueller-ma** [comment]
What happens when installing 1.12?

**Comment by bkircher** [comment]
1.12 update works like a charm here! Play Protect doesn't complain anymore

**Comment by bkircher** [comment]
Thanks!
