### ISSUE TITLE
Coffee does not keep the display awake outside of the app itself.

### ISSUE THREAD

**Issue by JimPix1** [mueller-ma/Coffee#60]
**Describe the bug**
Coffee keeps the display on inside the app, but not outside it, I have battery optimisation disabled in system settings.

**To Reproduce**
1. Turn on Coffee.
2. Leave the app.
3. The screen will turn off.

**Expected behavior**
Coffee is supposed to keep the display awake outside of the app.

**Device (please complete the following information):**
 - Device: Galaxy Tab A 2019
 - Android version: 10

**Additional context**
Downgrading did not solve this.

**Comment by mueller-ma** [comment]
Can you try to capture a log via adb?

**Comment by JimPix1** [comment]
> Can you try to capture a log via adb?

How would I do that?

**Comment by mueller-ma** [comment]
https://www.xda-developers.com/how-to-take-logs-in-android/

Honestly I don't think that there's a solution for this issue as long as Samsung keeps killing wakelock that are hold by foreground services.

**Comment by JimPix1** [comment]
I see, thanks
