### ISSUE TITLE
Tasker integration

### ISSUE THREAD

**Issue by carstengrimm** [mueller-ma/Coffee#85]
Is it possible to trigger on/off with tasker / terminal to somewhat be able to have conditional enabling where the phone does not go to sleep anymore. 

E.g. having a profile where coffee is enabled when connected to a power source or to a certain bt device

**Comment by mueller-ma** [comment]
Good idea!

For reference: https://tasker.joaoapps.com/plugins-intro.html

**Comment by steff75** [comment]
Hi and thanks for the development of Coffee!
Is the Tasker integration still in planning?

Tasker can do app shortcuts as an alternative to plugins, but the Coffee toggle shortcut is apparently not visible to Tasker.

The same is the case with the Tasker action to set the assistant, where Coffee also doesn't show up in the list of selectable assistant apps.

I tried it with the last 3 Coffee versions. My smartphone is the OnePlus 7 and all software is up to date.

Thanks!

**Comment by mueller-ma** [comment]
This feature request is in "I'll accept PRs, but probably won't implement it on my own".
