### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by shuvashish76** [mueller-ma/Coffee#90]
I've seen OSS projects use these sites for translation purpose
- [Crowdin](https://crowdin.com/)
- [Transifex](https://www.transifex.com/)
- [Weblate](https://weblate.org/en/)

I think Weblate is better as it's [opensource](https://github.com/WeblateOrg/weblate).

Features: https://weblate.org/en/features/
![144753433-4fc61e84-f12d-42d0-885e-1b9abd399061](https://user-images.githubusercontent.com/48226312/145707354-f2eb3482-ce93-474c-9a85-dfbb75124a0c.jpeg)
https://weblate.org/en/hosting/

**Comment by mueller-ma** [comment]
Actually I already requested a Weblate project for Coffee, but I haven't had time to set it up yet.

**Comment by mueller-ma** [comment]
Crowdin should be used for translations: https://crowdin.com/project/coffee-app
